# Generated by Django 3.2 on 2021-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgAnal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='picture_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='picture_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
