# Generated by Django 3.2 on 2021-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgAnal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='title',
        ),
        migrations.AddField(
            model_name='myimage',
            name='model_pic',
            field=models.ImageField(default='none/no-img.jpg', upload_to=''),
        ),
    ]
