# Generated by Django 3.2 on 2021-10-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImgAnal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealHotels',
            new_name='Hotels',
        ),
    ]
