# Generated by Django 3.2 on 2021-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgAnal', '0002_auto_20211006_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarks',
            name='eng_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='landmarks',
            name='kor_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
