# Generated by Django 3.2 on 2021-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgAnal', '0003_auto_20211014_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarks',
            name='eng_desc',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='kor_desc',
            field=models.TextField(default='', max_length=600),
        ),
    ]
