# Generated by Django 3.2 on 2021-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgAnal', '0004_auto_20211014_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='operation_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='service_option',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='star_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='telephone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
