# Generated by Django 3.2 on 2021-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgAnal', '0005_auto_20211015_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='star_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='telephone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
